- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: yes
  become: yes

- name: Deploy templated index page
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes
